import type { Deal, Owner } from '@/types/deal.types'

// ─── Owners ──────────────────────────────────────────────────────────────────

export const MOCK_OWNERS: Owner[] = [
  { id: 'u-1', name: 'Robert Ferreira', initials: 'RF', avatar_color: '#5b50e8' },
  { id: 'u-2', name: 'Ana Paula',       initials: 'AP', avatar_color: '#0891b2' },
  { id: 'u-3', name: 'Carlos Mendez',   initials: 'CM', avatar_color: '#059669' },
  { id: 'u-4', name: 'Julia Santos',    initials: 'JS', avatar_color: '#d97706' },
]

const [RF, AP, CM, JS_owner] = MOCK_OWNERS

// ─── Deals ───────────────────────────────────────────────────────────────────

export const MOCK_DEALS: Deal[] = [
  // ── Prospecção ──────────────────────────────────────────────────────────────
  {
    id: 'd-001',
    company_id: 'c-001',
    title: 'Plataforma Analytics Operacional',
    stage_id: 'prospecting',
    value: 3200000,
    currency: 'BRL',
    probability: 10,
    days_in_stage: 18,
    expected_close: '2026-12-01',
    tags: ['Energia'],
    owner_id: 'u-1',
    owner: RF,
    stakeholders: [
      { initials: 'MR', color: '#5b50e8', name: 'Marco Ribeiro' },
      { initials: 'AC', color: '#0891b2', name: 'Ana Costa' },
    ],
    next_activity: { type: 'meeting', label: 'Reunião kick-off', due_date: '2026-04-17' },
    last_activity_at: '2026-04-12',
    // Contact
    contact_name: 'Marco Ribeiro',
    contact_title: 'Head of Digital Transformation',
    contact_email: 'marco.ribeiro@petrobras.com.br',
    contact_phone: '+55 21 3224-1000',
    contact_linkedin: 'https://linkedin.com/in/marco-ribeiro-petro',
    // Company
    company_name: 'Petrobras',
    company_website: 'https://www.petrobras.com.br',
    company_sector: 'Energia',
    company_size: '1000+',
    company_arr_range: '>1M',
    lead_source: 'Inbound',
    created_at: '2026-03-25',
    updated_at: '2026-04-12',
  },
  {
    id: 'd-002',
    company_id: 'c-002',
    title: 'Suite ERP Cloud Manufacturing',
    stage_id: 'prospecting',
    value: 2800000,
    currency: 'BRL',
    probability: 10,
    days_in_stage: 7,
    expected_close: '2026-11-15',
    tags: ['Manufatura'],
    owner_id: 'u-2',
    owner: AP,
    stakeholders: [{ initials: 'PL', color: '#059669', name: 'Paulo Lima' }],
    next_activity: { type: 'call', label: 'Discovery call', due_date: '2026-04-20' },
    last_activity_at: '2026-04-09',
    contact_name: 'Paulo Lima',
    contact_title: 'VP de Operações',
    contact_email: 'paulo.lima@embraer.com.br',
    contact_phone: '+55 12 3927-5000',
    contact_linkedin: 'https://linkedin.com/in/paulo-lima-embraer',
    company_name: 'Embraer',
    company_website: 'https://www.embraer.com',
    company_sector: 'Manufatura',
    company_size: '1000+',
    company_arr_range: '>1M',
    lead_source: 'Outbound',
    created_at: '2026-04-07',
    updated_at: '2026-04-09',
  },
  {
    id: 'd-003',
    company_id: 'c-003',
    title: 'ESG Data & Reporting Platform',
    stage_id: 'prospecting',
    value: 1400000,
    currency: 'BRL',
    probability: 10,
    days_in_stage: 4,
    expected_close: '2027-01-30',
    tags: ['ESG'],
    owner_id: 'u-3',
    owner: CM,
    stakeholders: [
      { initials: 'FS', color: '#7c3aed', name: 'Fernanda Souza' },
      { initials: 'DM', color: '#d97706', name: 'Diego Martins' },
    ],
    last_activity_at: '2026-04-12',
    contact_name: 'Fernanda Souza',
    contact_title: 'Diretora de Sustentabilidade',
    contact_email: 'fernanda.souza@raizen.com',
    contact_phone: '+55 11 3702-9500',
    contact_linkedin: 'https://linkedin.com/in/fernanda-souza-raizen',
    company_name: 'Raízen',
    company_website: 'https://www.raizen.com.br',
    company_sector: 'Energia',
    company_size: '1000+',
    company_arr_range: '500k-1M',
    lead_source: 'Evento',
    created_at: '2026-04-11',
    updated_at: '2026-04-12',
  },

  // ── Qualificação ────────────────────────────────────────────────────────────
  {
    id: 'd-004',
    company_id: 'c-004',
    title: 'Data Intelligence & Mining Ops',
    stage_id: 'qualification',
    value: 4500000,
    currency: 'BRL',
    probability: 25,
    days_in_stage: 32,
    expected_close: '2026-10-31',
    tags: ['Dados'],
    owner_id: 'u-1',
    owner: RF,
    stakeholders: [
      { initials: 'RN', color: '#5b50e8', name: 'Ricardo Neves' },
      { initials: 'KA', color: '#dc2626', name: 'Karina Alves' },
      { initials: 'JS', color: '#059669', name: 'João Saraiva' },
    ],
    next_activity: { type: 'meeting', label: 'Workshop técnico', due_date: '2026-04-16' },
    last_activity_at: '2026-04-10',
    contact_name: 'Ricardo Neves',
    contact_title: 'Chief Data Officer',
    contact_email: 'ricardo.neves@vale.com',
    contact_phone: '+55 21 3814-8888',
    contact_linkedin: 'https://linkedin.com/in/ricardo-neves-vale',
    company_name: 'Vale',
    company_website: 'https://www.vale.com',
    company_sector: 'Mineração',
    company_size: '1000+',
    company_arr_range: '>1M',
    lead_source: 'Indicação',
    created_at: '2026-03-12',
    updated_at: '2026-04-10',
  },
  {
    id: 'd-005',
    company_id: 'c-005',
    title: 'Plataforma Industry 4.0 Connect',
    stage_id: 'qualification',
    value: 1900000,
    currency: 'BRL',
    probability: 25,
    days_in_stage: 21,
    expected_close: '2026-09-30',
    tags: ['Manufatura'],
    owner_id: 'u-2',
    owner: AP,
    stakeholders: [{ initials: 'BR', color: '#0891b2', name: 'Bruno Ramos' }],
    next_activity: { type: 'task', label: 'Enviar proposta técnica', due_date: '2026-04-13' },
    last_activity_at: '2026-04-08',
    contact_name: 'Bruno Ramos',
    contact_title: 'Gerente de Inovação Industrial',
    contact_email: 'bruno.ramos@weg.com.br',
    contact_phone: '+55 47 3372-4000',
    contact_linkedin: 'https://linkedin.com/in/bruno-ramos-weg',
    company_name: 'WEG',
    company_website: 'https://www.weg.com.br',
    company_sector: 'Manufatura',
    company_size: '1000+',
    company_arr_range: '500k-1M',
    lead_source: 'Outbound',
    created_at: '2026-03-22',
    updated_at: '2026-04-08',
  },

  // ── Proposta ────────────────────────────────────────────────────────────────
  {
    id: 'd-006',
    company_id: 'c-006',
    title: 'AI Risk & Compliance Engine',
    stage_id: 'proposal',
    value: 5200000,
    currency: 'BRL',
    probability: 50,
    days_in_stage: 45,
    expected_close: '2026-08-15',
    tags: ['Fintech'],
    owner_id: 'u-1',
    owner: RF,
    stakeholders: [
      { initials: 'LC', color: '#5b50e8', name: 'Lucia Carvalho' },
      { initials: 'TP', color: '#7c3aed', name: 'Thiago Pinheiro' },
    ],
    next_activity: { type: 'meeting', label: 'Apresentação ao board', due_date: '2026-04-23' },
    last_activity_at: '2026-04-14',
    contact_name: 'Lucia Carvalho',
    contact_title: 'CTO & Diretora de Risco',
    contact_email: 'lucia.carvalho@itau-unibanco.com.br',
    contact_phone: '+55 11 5019-1234',
    contact_linkedin: 'https://linkedin.com/in/lucia-carvalho-itau',
    company_name: 'Itaú Unibanco',
    company_website: 'https://www.itau.com.br',
    company_sector: 'Fintech',
    company_size: '1000+',
    company_arr_range: '>1M',
    lead_source: 'Indicação',
    created_at: '2026-02-28',
    updated_at: '2026-04-14',
  },
  {
    id: 'd-007',
    company_id: 'c-007',
    title: 'Enterprise SaaS Migration Suite',
    stage_id: 'proposal',
    value: 2100000,
    currency: 'BRL',
    probability: 50,
    days_in_stage: 28,
    expected_close: '2026-09-01',
    tags: ['SaaS'],
    owner_id: 'u-4',
    owner: JS_owner,
    stakeholders: [
      { initials: 'MF', color: '#059669', name: 'Marcelo Faria' },
      { initials: 'SC', color: '#d97706', name: 'Sara Castro' },
    ],
    next_activity: { type: 'email', label: 'Follow-up proposta', due_date: '2026-04-18' },
    last_activity_at: '2026-04-12',
    contact_name: 'Marcelo Faria',
    contact_title: 'VP de Produto',
    contact_email: 'marcelo.faria@totvs.com.br',
    contact_phone: '+55 11 4003-0015',
    contact_linkedin: 'https://linkedin.com/in/marcelo-faria-totvs',
    company_name: 'TOTVS',
    company_website: 'https://www.totvs.com',
    company_sector: 'SaaS',
    company_size: '1000+',
    company_arr_range: '>1M',
    lead_source: 'Inbound',
    created_at: '2026-03-15',
    updated_at: '2026-04-12',
  },

  // ── Negociação ──────────────────────────────────────────────────────────────
  {
    id: 'd-008',
    company_id: 'c-008',
    title: 'Core Banking Modernization',
    stage_id: 'negotiation',
    value: 4800000,
    currency: 'BRL',
    probability: 75,
    days_in_stage: 62,
    expected_close: '2026-07-01',
    tags: ['Fintech'],
    owner_id: 'u-3',
    owner: CM,
    stakeholders: [
      { initials: 'GV', color: '#5b50e8', name: 'Guilherme Vieira' },
      { initials: 'NB', color: '#dc2626', name: 'Natalia Braga' },
    ],
    next_activity: { type: 'meeting', label: 'Revisão contratual', due_date: '2026-04-16' },
    last_activity_at: '2026-04-15',
    contact_name: 'Guilherme Vieira',
    contact_title: 'Diretor de Tecnologia',
    contact_email: 'guilherme.vieira@bradesco.com.br',
    contact_phone: '+55 11 2178-5678',
    contact_linkedin: 'https://linkedin.com/in/guilherme-vieira-bradesco',
    company_name: 'Bradesco',
    company_website: 'https://www.bradesco.com.br',
    company_sector: 'Fintech',
    company_size: '1000+',
    company_arr_range: '>1M',
    lead_source: 'Indicação',
    created_at: '2026-02-11',
    updated_at: '2026-04-15',
  },
  {
    id: 'd-009',
    company_id: 'c-009',
    title: 'Wealth Intelligence Platform',
    stage_id: 'negotiation',
    value: 2700000,
    currency: 'BRL',
    probability: 75,
    days_in_stage: 38,
    expected_close: '2026-06-30',
    tags: ['IA'],
    owner_id: 'u-4',
    owner: JS_owner,
    stakeholders: [{ initials: 'CB', color: '#7c3aed', name: 'Carolina Barros' }],
    next_activity: { type: 'call', label: 'Alinhamento de pricing', due_date: '2026-04-17' },
    last_activity_at: '2026-04-16',
    contact_name: 'Carolina Barros',
    contact_title: 'Head of Wealth Management Tech',
    contact_email: 'carolina.barros@xp.com.br',
    contact_phone: '+55 11 3027-2237',
    contact_linkedin: 'https://linkedin.com/in/carolina-barros-xp',
    company_name: 'XP Inc.',
    company_website: 'https://www.xpi.com.br',
    company_sector: 'Fintech',
    company_size: '1000+',
    company_arr_range: '>1M',
    lead_source: 'Evento',
    created_at: '2026-03-05',
    updated_at: '2026-04-16',
  },

  // ── Fechado Ganho ────────────────────────────────────────────────────────────
  {
    id: 'd-010',
    company_id: 'c-010',
    title: 'Supply Chain Intelligence Suite',
    stage_id: 'closed_won',
    value: 3600000,
    currency: 'BRL',
    probability: 100,
    days_in_stage: 90,
    expected_close: '2026-04-10',
    tags: ['Dados'],
    owner_id: 'u-1',
    owner: RF,
    stakeholders: [
      { initials: 'RA', color: '#059669', name: 'Rafael Andrade' },
      { initials: 'IL', color: '#0891b2', name: 'Isabel Lima' },
    ],
    last_activity_at: '2026-04-10',
    contact_name: 'Rafael Andrade',
    contact_title: 'VP de Supply Chain',
    contact_email: 'rafael.andrade@ambev.com.br',
    contact_phone: '+55 11 2122-1200',
    contact_linkedin: 'https://linkedin.com/in/rafael-andrade-ambev',
    company_name: 'Ambev',
    company_website: 'https://www.ambev.com.br',
    company_sector: 'Dados',
    company_size: '1000+',
    company_arr_range: '>1M',
    lead_source: 'Outbound',
    created_at: '2026-01-10',
    updated_at: '2026-04-10',
  },

  // ── Fechado Perdido ──────────────────────────────────────────────────────────
  {
    id: 'd-011',
    company_id: 'c-011',
    title: 'E-commerce Analytics Enterprise',
    stage_id: 'closed_lost',
    value: 1800000,
    currency: 'BRL',
    probability: 0,
    days_in_stage: 125,
    expected_close: '2026-04-01',
    tags: ['Varejo'],
    owner_id: 'u-4',
    owner: JS_owner,
    stakeholders: [{ initials: 'VM', color: '#9ca3af', name: 'Vinicius Moura' }],
    last_activity_at: '2026-04-01',
    contact_name: 'Vinicius Moura',
    contact_title: 'Diretor de E-commerce',
    contact_email: 'vinicius.moura@magazineluiza.com.br',
    contact_phone: '+55 11 3504-2000',
    contact_linkedin: 'https://linkedin.com/in/vinicius-moura-magalu',
    company_name: 'Magazine Luiza',
    company_website: 'https://www.magazineluiza.com.br',
    company_sector: 'Varejo',
    company_size: '1000+',
    company_arr_range: '>1M',
    lead_source: 'Inbound',
    created_at: '2025-12-01',
    updated_at: '2026-04-01',
  },
]
