import type { Deal, Owner, DealActivity, DealMeeting } from '@/types/deal.types'

// ─── Owners ──────────────────────────────────────────────────────────────────

export const MOCK_OWNERS: Owner[] = [
  { id: 'u-1', name: 'Robert Ferreira', initials: 'RF', avatar_color: '#5b50e8' },
  { id: 'u-2', name: 'Ana Paula',       initials: 'AP', avatar_color: '#0891b2' },
  { id: 'u-3', name: 'Carlos Mendez',   initials: 'CM', avatar_color: '#059669' },
  { id: 'u-4', name: 'Julia Santos',    initials: 'JS', avatar_color: '#d97706' },
]

const [RF, AP, CM, JS_owner] = MOCK_OWNERS

// ─── Deals ───────────────────────────────────────────────────────────────────

export const MOCK_DEALS: Deal[] = [
  // ── Prospecção ──────────────────────────────────────────────────────────────
  {
    id: 'd-001',
    company_id: 'c-001',
    title: 'Plataforma Analytics Operacional',
    stage_id: 'prospecting',
    value: 3200000,
    currency: 'BRL',
    probability: 10,
    days_in_stage: 18,
    expected_close: '2026-12-01',
    tags: ['Energia'],
    owner_id: 'u-1',
    owner: RF,
    stakeholders: [
      { initials: 'MR', color: '#5b50e8', name: 'Marco Ribeiro' },
      { initials: 'AC', color: '#0891b2', name: 'Ana Costa' },
    ],
    next_activity: { type: 'meeting', label: 'Reunião kick-off', due_date: '2026-04-17' },
    last_activity_at: '2026-04-12',
    // Contact
    contact_name: 'Marco Ribeiro',
    contact_title: 'Head of Digital Transformation',
    contact_email: 'marco.ribeiro@petrobras.com.br',
    contact_phone: '+55 21 3224-1000',
    contact_linkedin: 'https://linkedin.com/in/marco-ribeiro-petro',
    // Company
    company_name: 'Petrobras',
    company_website: 'https://www.petrobras.com.br',
    company_sector: 'Energia',
    company_size: '1000+',
    company_arr_range: '>1M',
    lead_source: 'Inbound',
    created_at: '2026-03-25',
    updated_at: '2026-04-12',
  },
  {
    id: 'd-002',
    company_id: 'c-002',
    title: 'Suite ERP Cloud Manufacturing',
    stage_id: 'prospecting',
    value: 2800000,
    currency: 'BRL',
    probability: 10,
    days_in_stage: 7,
    expected_close: '2026-11-15',
    tags: ['Manufatura'],
    owner_id: 'u-2',
    owner: AP,
    stakeholders: [{ initials: 'PL', color: '#059669', name: 'Paulo Lima' }],
    next_activity: { type: 'call', label: 'Discovery call', due_date: '2026-04-20' },
    last_activity_at: '2026-04-09',
    contact_name: 'Paulo Lima',
    contact_title: 'VP de Operações',
    contact_email: 'paulo.lima@embraer.com.br',
    contact_phone: '+55 12 3927-5000',
    contact_linkedin: 'https://linkedin.com/in/paulo-lima-embraer',
    company_name: 'Embraer',
    company_website: 'https://www.embraer.com',
    company_sector: 'Manufatura',
    company_size: '1000+',
    company_arr_range: '>1M',
    lead_source: 'Outbound',
    created_at: '2026-04-07',
    updated_at: '2026-04-09',
  },
  {
    id: 'd-003',
    company_id: 'c-003',
    title: 'ESG Data & Reporting Platform',
    stage_id: 'prospecting',
    value: 1400000,
    currency: 'BRL',
    probability: 10,
    days_in_stage: 4,
    expected_close: '2027-01-30',
    tags: ['ESG'],
    owner_id: 'u-3',
    owner: CM,
    stakeholders: [
      { initials: 'FS', color: '#7c3aed', name: 'Fernanda Souza' },
      { initials: 'DM', color: '#d97706', name: 'Diego Martins' },
    ],
    last_activity_at: '2026-04-12',
    contact_name: 'Fernanda Souza',
    contact_title: 'Diretora de Sustentabilidade',
    contact_email: 'fernanda.souza@raizen.com',
    contact_phone: '+55 11 3702-9500',
    contact_linkedin: 'https://linkedin.com/in/fernanda-souza-raizen',
    company_name: 'Raízen',
    company_website: 'https://www.raizen.com.br',
    company_sector: 'Energia',
    company_size: '1000+',
    company_arr_range: '500k-1M',
    lead_source: 'Evento',
    created_at: '2026-04-11',
    updated_at: '2026-04-12',
  },

  // ── Qualificação ────────────────────────────────────────────────────────────
  {
    id: 'd-004',
    company_id: 'c-004',
    title: 'Data Intelligence & Mining Ops',
    stage_id: 'qualification',
    value: 4500000,
    currency: 'BRL',
    probability: 25,
    days_in_stage: 32,
    expected_close: '2026-10-31',
    tags: ['Dados'],
    owner_id: 'u-1',
    owner: RF,
    stakeholders: [
      { initials: 'RN', color: '#5b50e8', name: 'Ricardo Neves' },
      { initials: 'KA', color: '#dc2626', name: 'Karina Alves' },
      { initials: 'JS', color: '#059669', name: 'João Saraiva' },
    ],
    next_activity: { type: 'meeting', label: 'Workshop técnico', due_date: '2026-04-16' },
    last_activity_at: '2026-04-10',
    contact_name: 'Ricardo Neves',
    contact_title: 'Chief Data Officer',
    contact_email: 'ricardo.neves@vale.com',
    contact_phone: '+55 21 3814-8888',
    contact_linkedin: 'https://linkedin.com/in/ricardo-neves-vale',
    company_name: 'Vale',
    company_website: 'https://www.vale.com',
    company_sector: 'Mineração',
    company_size: '1000+',
    company_arr_range: '>1M',
    lead_source: 'Indicação',
    created_at: '2026-03-12',
    updated_at: '2026-04-10',
  },
  {
    id: 'd-005',
    company_id: 'c-005',
    title: 'Plataforma Industry 4.0 Connect',
    stage_id: 'qualification',
    value: 1900000,
    currency: 'BRL',
    probability: 25,
    days_in_stage: 21,
    expected_close: '2026-09-30',
    tags: ['Manufatura'],
    owner_id: 'u-2',
    owner: AP,
    stakeholders: [{ initials: 'BR', color: '#0891b2', name: 'Bruno Ramos' }],
    next_activity: { type: 'task', label: 'Enviar proposta técnica', due_date: '2026-04-13' },
    last_activity_at: '2026-04-08',
    contact_name: 'Bruno Ramos',
    contact_title: 'Gerente de Inovação Industrial',
    contact_email: 'bruno.ramos@weg.com.br',
    contact_phone: '+55 47 3372-4000',
    contact_linkedin: 'https://linkedin.com/in/bruno-ramos-weg',
    company_name: 'WEG',
    company_website: 'https://www.weg.com.br',
    company_sector: 'Manufatura',
    company_size: '1000+',
    company_arr_range: '500k-1M',
    lead_source: 'Outbound',
    created_at: '2026-03-22',
    updated_at: '2026-04-08',
  },

  // ── Proposta ────────────────────────────────────────────────────────────────
  {
    id: 'd-006',
    company_id: 'c-006',
    title: 'AI Risk & Compliance Engine',
    stage_id: 'proposal',
    value: 5200000,
    currency: 'BRL',
    probability: 50,
    days_in_stage: 45,
    expected_close: '2026-08-15',
    tags: ['Fintech'],
    owner_id: 'u-1',
    owner: RF,
    stakeholders: [
      { initials: 'LC', color: '#5b50e8', name: 'Lucia Carvalho' },
      { initials: 'TP', color: '#7c3aed', name: 'Thiago Pinheiro' },
    ],
    next_activity: { type: 'meeting', label: 'Apresentação ao board', due_date: '2026-04-23' },
    last_activity_at: '2026-04-14',
    contact_name: 'Lucia Carvalho',
    contact_title: 'CTO & Diretora de Risco',
    contact_email: 'lucia.carvalho@itau-unibanco.com.br',
    contact_phone: '+55 11 5019-1234',
    contact_linkedin: 'https://linkedin.com/in/lucia-carvalho-itau',
    company_name: 'Itaú Unibanco',
    company_website: 'https://www.itau.com.br',
    company_sector: 'Fintech',
    company_size: '1000+',
    company_arr_range: '>1M',
    lead_source: 'Indicação',
    created_at: '2026-02-28',
    updated_at: '2026-04-14',
  },
  {
    id: 'd-007',
    company_id: 'c-007',
    title: 'Enterprise SaaS Migration Suite',
    stage_id: 'proposal',
    value: 2100000,
    currency: 'BRL',
    probability: 50,
    days_in_stage: 28,
    expected_close: '2026-09-01',
    tags: ['SaaS'],
    owner_id: 'u-4',
    owner: JS_owner,
    stakeholders: [
      { initials: 'MF', color: '#059669', name: 'Marcelo Faria' },
      { initials: 'SC', color: '#d97706', name: 'Sara Castro' },
    ],
    next_activity: { type: 'email', label: 'Follow-up proposta', due_date: '2026-04-18' },
    last_activity_at: '2026-04-12',
    contact_name: 'Marcelo Faria',
    contact_title: 'VP de Produto',
    contact_email: 'marcelo.faria@totvs.com.br',
    contact_phone: '+55 11 4003-0015',
    contact_linkedin: 'https://linkedin.com/in/marcelo-faria-totvs',
    company_name: 'TOTVS',
    company_website: 'https://www.totvs.com',
    company_sector: 'SaaS',
    company_size: '1000+',
    company_arr_range: '>1M',
    lead_source: 'Inbound',
    created_at: '2026-03-15',
    updated_at: '2026-04-12',
  },

  // ── Negociação ──────────────────────────────────────────────────────────────
  {
    id: 'd-008',
    company_id: 'c-008',
    title: 'Core Banking Modernization',
    stage_id: 'negotiation',
    value: 4800000,
    currency: 'BRL',
    probability: 75,
    days_in_stage: 62,
    expected_close: '2026-07-01',
    tags: ['Fintech'],
    owner_id: 'u-3',
    owner: CM,
    stakeholders: [
      { initials: 'GV', color: '#5b50e8', name: 'Guilherme Vieira' },
      { initials: 'NB', color: '#dc2626', name: 'Natalia Braga' },
    ],
    next_activity: { type: 'meeting', label: 'Revisão contratual', due_date: '2026-04-16' },
    last_activity_at: '2026-04-15',
    contact_name: 'Guilherme Vieira',
    contact_title: 'Diretor de Tecnologia',
    contact_email: 'guilherme.vieira@bradesco.com.br',
    contact_phone: '+55 11 2178-5678',
    contact_linkedin: 'https://linkedin.com/in/guilherme-vieira-bradesco',
    company_name: 'Bradesco',
    company_website: 'https://www.bradesco.com.br',
    company_sector: 'Fintech',
    company_size: '1000+',
    company_arr_range: '>1M',
    lead_source: 'Indicação',
    created_at: '2026-02-11',
    updated_at: '2026-04-15',
  },
  {
    id: 'd-009',
    company_id: 'c-009',
    title: 'Wealth Intelligence Platform',
    stage_id: 'negotiation',
    value: 2700000,
    currency: 'BRL',
    probability: 75,
    days_in_stage: 38,
    expected_close: '2026-06-30',
    tags: ['IA'],
    owner_id: 'u-4',
    owner: JS_owner,
    stakeholders: [{ initials: 'CB', color: '#7c3aed', name: 'Carolina Barros' }],
    next_activity: { type: 'call', label: 'Alinhamento de pricing', due_date: '2026-04-17' },
    last_activity_at: '2026-04-16',
    contact_name: 'Carolina Barros',
    contact_title: 'Head of Wealth Management Tech',
    contact_email: 'carolina.barros@xp.com.br',
    contact_phone: '+55 11 3027-2237',
    contact_linkedin: 'https://linkedin.com/in/carolina-barros-xp',
    company_name: 'XP Inc.',
    company_website: 'https://www.xpi.com.br',
    company_sector: 'Fintech',
    company_size: '1000+',
    company_arr_range: '>1M',
    lead_source: 'Evento',
    created_at: '2026-03-05',
    updated_at: '2026-04-16',
  },

  // ── Fechado Ganho ────────────────────────────────────────────────────────────
  {
    id: 'd-010',
    company_id: 'c-010',
    title: 'Supply Chain Intelligence Suite',
    stage_id: 'closed_won',
    value: 3600000,
    currency: 'BRL',
    probability: 100,
    days_in_stage: 90,
    expected_close: '2026-04-10',
    tags: ['Dados'],
    owner_id: 'u-1',
    owner: RF,
    stakeholders: [
      { initials: 'RA', color: '#059669', name: 'Rafael Andrade' },
      { initials: 'IL', color: '#0891b2', name: 'Isabel Lima' },
    ],
    last_activity_at: '2026-04-10',
    contact_name: 'Rafael Andrade',
    contact_title: 'VP de Supply Chain',
    contact_email: 'rafael.andrade@ambev.com.br',
    contact_phone: '+55 11 2122-1200',
    contact_linkedin: 'https://linkedin.com/in/rafael-andrade-ambev',
    company_name: 'Ambev',
    company_website: 'https://www.ambev.com.br',
    company_sector: 'Dados',
    company_size: '1000+',
    company_arr_range: '>1M',
    lead_source: 'Outbound',
    created_at: '2026-01-10',
    updated_at: '2026-04-10',
  },

  // ── Fechado Perdido ──────────────────────────────────────────────────────────
  {
    id: 'd-011',
    company_id: 'c-011',
    title: 'E-commerce Analytics Enterprise',
    stage_id: 'closed_lost',
    value: 1800000,
    currency: 'BRL',
    probability: 0,
    days_in_stage: 125,
    expected_close: '2026-04-01',
    tags: ['Varejo'],
    owner_id: 'u-4',
    owner: JS_owner,
    stakeholders: [{ initials: 'VM', color: '#9ca3af', name: 'Vinicius Moura' }],
    last_activity_at: '2026-04-01',
    contact_name: 'Vinicius Moura',
    contact_title: 'Diretor de E-commerce',
    contact_email: 'vinicius.moura@magazineluiza.com.br',
    contact_phone: '+55 11 3504-2000',
    contact_linkedin: 'https://linkedin.com/in/vinicius-moura-magalu',
    company_name: 'Magazine Luiza',
    company_website: 'https://www.magazineluiza.com.br',
    company_sector: 'Varejo',
    company_size: '1000+',
    company_arr_range: '>1M',
    lead_source: 'Inbound',
    created_at: '2025-12-01',
    updated_at: '2026-04-01',
  },
]

// ─── Activities per deal ──────────────────────────────────────────────────────

export const MOCK_ACTIVITIES: Record<string, DealActivity[]> = {
  'd-001': [
    { id: 'a-001-1', deal_id: 'd-001', type: 'meeting', subject: 'Reunião de descoberta inicial', body: 'Apresentamos o produto ao time de Digital Transformation. Marco demonstrou interesse na automação de relatórios operacionais. Próximo passo: workshop técnico.', owner: RF, created_at: '2026-04-12', meeting_id: 'm-001' },
    { id: 'a-001-2', deal_id: 'd-001', type: 'email', subject: 'Envio de materiais de onboarding', body: 'Compartilhei deck executivo e case studies do setor de energia. Marco confirmou recebimento e disse que vai repassar para o CTO.', owner: RF, created_at: '2026-04-08' },
    { id: 'a-001-3', deal_id: 'd-001', type: 'call', subject: 'Cold call inicial — qualificação BANT', body: 'Marco é o champion. Orçamento existe (~R$ 5M aprovado para digitalização). Decisão em Q4. Precisa de aprovação do board.', owner: RF, created_at: '2026-03-28' },
  ],
  'd-004': [
    { id: 'a-004-1', deal_id: 'd-004', type: 'meeting', subject: 'Workshop técnico com time de dados', body: 'Reunião de 3h com 6 pessoas do time de CDO. Fizemos demo ao vivo com dados reais da Vale. Forte engajamento — Ricardo pediu POC para 30 dias.', owner: RF, created_at: '2026-04-10', meeting_id: 'm-004' },
    { id: 'a-004-2', deal_id: 'd-004', type: 'task', subject: 'Envio de proposta técnica v1', body: 'Proposta de R$ 4.5M com escopo de 18 meses enviada para Ricardo e Karina.', owner: RF, created_at: '2026-03-25' },
    { id: 'a-004-3', deal_id: 'd-004', type: 'email', subject: 'Follow-up após apresentação exec', body: 'Ricardo confirmou que João Saraiva (CFO) está aprovando o budget. Processo de procurement deve ser iniciado em breve.', owner: RF, created_at: '2026-03-18' },
    { id: 'a-004-4', deal_id: 'd-004', type: 'call', subject: 'Qualificação com CDO', body: 'Ricardo é economic buyer. Pain principal: dados de mineração fragmentados em 12 sistemas legados. ROI estimado em 18 meses.', owner: RF, created_at: '2026-03-12' },
  ],
  'd-006': [
    { id: 'a-006-1', deal_id: 'd-006', type: 'meeting', subject: 'Apresentação executiva ao C-level', body: 'Apresentamos para Lucia Carvalho (CTO) e Thiago Pinheiro (Chief Risk Officer). Aprovação técnica obtida. Falta aprovação do board na reunião de 23/04.', owner: RF, created_at: '2026-04-14', meeting_id: 'm-006' },
    { id: 'a-006-2', deal_id: 'd-006', type: 'email', subject: 'Proposta final — R$ 5.2M', body: 'Enviamos proposta revisada após feedback do time jurídico. SLA de 99.9% incluído. Cláusula de compliance com BACEN incorporada.', owner: RF, created_at: '2026-04-05' },
    { id: 'a-006-3', deal_id: 'd-006', type: 'meeting', subject: 'Workshop de segurança e compliance', body: 'Time de segurança do Itaú fez due diligence técnica por 4h. Todos os requisitos atendidos. Lucia ficou satisfeita com a arquitetura de zero-trust.', owner: RF, created_at: '2026-03-20', meeting_id: 'm-006b' },
    { id: 'a-006-4', deal_id: 'd-006', type: 'call', subject: 'Negociação de pricing', body: 'Lucia solicitou desconto de 10% para 3 anos. Contrapropomos 7% com suporte premium incluído. Em análise.', owner: RF, created_at: '2026-03-10' },
  ],
  'd-008': [
    { id: 'a-008-1', deal_id: 'd-008', type: 'meeting', subject: 'Revisão de minuta contratual', body: 'Jurídico do Bradesco levantou 3 pontos: cláusula de exclusividade, SLA de disaster recovery, e limitação de responsabilidade. Equipe jurídica respondendo em 5 dias úteis.', owner: CM, created_at: '2026-04-15', meeting_id: 'm-008' },
    { id: 'a-008-2', deal_id: 'd-008', type: 'email', subject: 'Aprovação técnica — sign-off do CTO', body: 'Guilherme confirmou aprovação técnica completa. Natalia Braga (Procurement) assumiu o processo de contratação.', owner: CM, created_at: '2026-04-08' },
    { id: 'a-008-3', deal_id: 'd-008', type: 'meeting', subject: 'Demo final com time de TI', body: '12 participantes. Demo de 2h da plataforma de core banking. Migração simulada de dados ao vivo. Aprovação unânime do time técnico.', owner: CM, created_at: '2026-03-28', meeting_id: 'm-008b' },
  ],
  'd-009': [
    { id: 'a-009-1', deal_id: 'd-009', type: 'call', subject: 'Alinhamento de pricing e condições', body: 'Carolina solicitou revisão do modelo de licenciamento. Proposta de precificação por AUM em análise. Decisão esta semana.', owner: JS_owner, created_at: '2026-04-16' },
    { id: 'a-009-2', deal_id: 'd-009', type: 'meeting', subject: 'Workshop com equipe de wealth management', body: 'Apresentamos módulo de AI para gestão de portfólio. Carolina trouxe 4 gestores sênior. Feedback muito positivo — querem personalizar alertas por perfil de cliente.', owner: JS_owner, created_at: '2026-04-02', meeting_id: 'm-009' },
  ],
}

// ─── Meetings with Plaud Note ─────────────────────────────────────────────────

export const MOCK_MEETINGS: DealMeeting[] = [
  {
    id: 'm-001',
    deal_id: 'd-001',
    title: 'Reunião de descoberta — Petrobras',
    scheduled_at: '2026-04-12T10:00:00',
    duration_minutes: 60,
    attendees: ['Marco Ribeiro', 'Ana Costa', 'Robert Ferreira'],
    plaud_note_id: 'plaud-4892',
    transcript_excerpt: 'Marco Ribeiro: "Nossa principal dor é a fragmentação dos dados operacionais. Temos 8 sistemas que não conversam entre si e isso nos custou pelo menos R$200M em ineficiências no último ano..." Robert Ferreira: "Entendido. Nossa plataforma unifica essas fontes com latência sub-segundo e gera relatórios executivos automaticamente. Posso mostrar como a Petrobras Chile implementou isso em 90 dias..."',
    ai_summary: 'Reunião de descoberta com cliente qualificado. Marco Ribeiro (champion) identificou dor crítica em fragmentação de dados. Budget de R$ 5M aprovado para digitalização em Q3. Decisão final depende de aprovação do board em julho.',
    key_points: [
      'Dor principal: 8 sistemas legados desintegrados',
      'Perda estimada de R$ 200M/ano em ineficiências',
      'Budget aprovado: ~R$ 5M para digitalização',
      'Champion engajado — repassará para CTO',
    ],
    action_items: [
      'Enviar deck executivo e 2 case studies do setor energético',
      'Agendar workshop técnico com equipe do CTO',
      'Preparar proposta com ROI baseado nos números mencionados',
    ],
    owner: RF,
  },
  {
    id: 'm-004',
    deal_id: 'd-004',
    title: 'Workshop técnico — Vale (CDO team)',
    scheduled_at: '2026-04-10T14:00:00',
    duration_minutes: 180,
    attendees: ['Ricardo Neves', 'Karina Alves', 'João Saraiva', 'Robert Ferreira'],
    plaud_note_id: 'plaud-4901',
    transcript_excerpt: 'Ricardo Neves: "Ficamos impressionados com a velocidade do processamento. Nossa maior preocupação era a latência na integração com nosso data lake na AWS..." Robert Ferreira: "Temos conector nativo para S3 e Redshift. A Vale Chile processa 2 bilhões de eventos/dia com latência média de 340ms..." Karina Alves: "E em relação à segurança, como é tratado o acesso aos dados de produção?"',
    ai_summary: 'Workshop técnico de alta qualidade. Time técnico da Vale validou todos os requisitos. Ricardo solicitou POC de 30 dias com dados reais. João Saraiva (CFO) presente confirma aprovação orçamentária em curso. Risco: processo de procurement pode levar 60+ dias.',
    key_points: [
      'Demo ao vivo com dados reais gerou forte engajamento',
      'POC de 30 dias aprovado por Ricardo Neves (CDO)',
      'CFO presente — budget em aprovação formal',
      'Requisitos técnicos 100% atendidos',
    ],
    action_items: [
      'Preparar ambiente de POC com conector AWS nativo',
      'Enviar documento de arquitetura de segurança para Karina',
      'Alinhar cronograma de POC com João Saraiva (CFO)',
    ],
    owner: RF,
  },
  {
    id: 'm-006',
    deal_id: 'd-006',
    title: 'Apresentação ao C-level — Itaú Unibanco',
    scheduled_at: '2026-04-14T09:00:00',
    duration_minutes: 90,
    attendees: ['Lucia Carvalho', 'Thiago Pinheiro', 'Robert Ferreira'],
    plaud_note_id: 'plaud-4915',
    transcript_excerpt: 'Lucia Carvalho: "O board aprova investimentos acima de R$ 3M. Preciso levar para a reunião de 23/04 com um ROI muito bem embasado..." Thiago Pinheiro: "Do ponto de vista de risco, o BACEN exige que o modelo de scoring seja auditável. Vocês têm isso?" Robert Ferreira: "Sim, nosso engine gera relatório de explicabilidade (XAI) por transação. Isso já está em produção no BTG..."',
    ai_summary: 'Aprovação técnica obtida de Lucia e Thiago. Decisão final na reunião do board em 23/04. ROI precisa ser muito sólido — Lucia vai usar para justificar ao conselho. Competidor: solução interna do time de data science (risco principal).',
    key_points: [
      'Aprovação técnica de CTO e Chief Risk Officer',
      'Board meeting para decisão final em 23/04',
      'Requisito BACEN de auditabilidade (XAI) atendido',
      'Risco: solução interna concorrendo',
    ],
    action_items: [
      'Preparar deck de ROI com benchmarks do setor bancário',
      'Enviar reference letter do BTG (cliente atual)',
      'Agendar call de preparação com Lucia antes do board meeting',
    ],
    owner: RF,
  },
  {
    id: 'm-008',
    deal_id: 'd-008',
    title: 'Revisão contratual — Bradesco',
    scheduled_at: '2026-04-15T15:00:00',
    duration_minutes: 120,
    attendees: ['Guilherme Vieira', 'Natalia Braga', 'Carlos Mendez'],
    plaud_note_id: 'plaud-4922',
    transcript_excerpt: 'Natalia Braga: "O contrato padrão do Bradesco não permite cláusula de exclusividade por mais de 12 meses. Vamos precisar ajustar isso..." Carlos Mendez: "Entendido. Podemos trabalhar com renovação automática anual com lock-in de pricing por 3 anos..." Guilherme Vieira: "A aprovação técnica já temos. Agora é só o jurídico finalizar."',
    ai_summary: 'Última etapa antes de assinatura. 3 pontos jurídicos pendentes — todos com solução clara. Guilherme confirmou aprovação técnica. Natalia Braga (Procurement) conduz o processo final. Estimativa de fechamento: 1ª semana de maio.',
    key_points: [
      'Aprovação técnica confirmada por Guilherme Vieira',
      '3 pontos jurídicos pendentes — todos negociáveis',
      'Natalia Braga conduz procurement final',
      'Assinatura estimada para primeira semana de maio',
    ],
    action_items: [
      'Enviar minuta revisada com cláusula de exclusividade ajustada',
      'Confirmar SLA de disaster recovery com time técnico',
      'Agendar call de fechamento para 30/04',
    ],
    owner: CM,
  },
  {
    id: 'm-009',
    deal_id: 'd-009',
    title: 'Workshop wealth management — XP Inc.',
    scheduled_at: '2026-04-02T10:00:00',
    duration_minutes: 90,
    attendees: ['Carolina Barros', 'Gestores sênior XP', 'Julia Santos'],
    plaud_note_id: 'plaud-4908',
    transcript_excerpt: 'Carolina Barros: "Nossos gestores precisam de alertas em tempo real por perfil de cliente. Hoje fazemos isso manualmente e perdemos oportunidades de alpha..." Julia Santos: "O módulo de alertas é totalmente configurável por regra de negócio. Posso mostrar como a equipe de wealth da Vinci configurou 47 alertas personalizados..."',
    ai_summary: 'Workshop muito positivo. Carolina e equipe validaram produto. Diferencial competitivo claro: personalização de alertas por perfil de cliente. Decisão de pricing pendente — Carolina quer modelo por AUM em vez de licença flat.',
    key_points: [
      'Forte interesse do time de wealth management',
      'Diferencial: alertas customizáveis por perfil de cliente',
      'Modelo de pricing em debate: AUM vs licença flat',
      'Decisão esperada até fim de abril',
    ],
    action_items: [
      'Modelar proposta com pricing por AUM',
      'Compartilhar benchmarks de pricing do mercado',
      'Agendar call de fechamento esta semana',
    ],
    owner: JS_owner,
  },
]
